name: Pickled-Canary CI with Gradle

on: [workflow_dispatch, push, pull_request]

permissions:
  contents: read

jobs:
  build_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nightly
        run: rustup toolchain install nightly --component rustfmt clippy
      - name: Format Rust
        working-directory: search
        run: cargo +nightly fmt --all -- --color=always --check
      - name: Check Rust with Clippy
        working-directory: search
        run: cargo +nightly clippy --workspace -- -D warnings
      - name: Build
        working-directory: search
        run: cargo +nightly build --verbose
      - name: Run tests
        working-directory: search
        run: cargo +nightly test --verbose
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        # - GHIDRA_VERSION: '9.2.2'
        #   GHIDRA_BUILD_DATE: "20201229"
        # - GHIDRA_VERSION: '9.2.4'
        #   GHIDRA_BUILD_DATE: "20210427"
        # - GHIDRA_VERSION: "10.0"
        #   GHIDRA_BUILD_DATE: "20210621"
        # - GHIDRA_VERSION: "10.0.1"
        #   GHIDRA_BUILD_DATE: "20210708"
        # - GHIDRA_VERSION: "10.0.2"
        #   GHIDRA_BUILD_DATE: "20210804"
        # - GHIDRA_VERSION: "10.0.3"
        #   GHIDRA_BUILD_DATE: "20210908"
        # - GHIDRA_VERSION: "10.1"
        #   GHIDRA_BUILD_DATE: "20211210"
        # - GHIDRA_VERSION: "10.1.1"
        #   GHIDRA_BUILD_DATE: "20211221"
        # - GHIDRA_VERSION: "10.1.2"
        #   GHIDRA_BUILD_DATE: "20220125"
        # - GHIDRA_VERSION: "10.1.3"
        #   GHIDRA_BUILD_DATE: "20220421"
        # - GHIDRA_VERSION: "10.1.4"
        #   GHIDRA_BUILD_DATE: "20220519"
        # - GHIDRA_VERSION: "10.1.5"
        #   GHIDRA_BUILD_DATE: "20220726"
        # - GHIDRA_VERSION: "10.2"
        #   GHIDRA_BUILD_DATE: "20221101"
        # - GHIDRA_VERSION: "10.2.1"
        #   GHIDRA_BUILD_DATE: "20221110"
        # - GHIDRA_VERSION: "10.2.2"
        #   GHIDRA_BUILD_DATE: "20221115"
        # - GHIDRA_VERSION: "10.2.3"
        #   GHIDRA_BUILD_DATE: "20230208"
        # - GHIDRA_VERSION: "10.3"
        #   GHIDRA_BUILD_DATE: "20230510"
        # - GHIDRA_VERSION: "10.3.1"
        #   GHIDRA_BUILD_DATE: "20230614"
        # - GHIDRA_VERSION: "10.3.2"
        #   GHIDRA_BUILD_DATE: "20230711"
          - GHIDRA_VERSION: "10.3.3"
            GHIDRA_BUILD_DATE: "20230829"
          - GHIDRA_VERSION: "10.4"
            GHIDRA_BUILD_DATE: "20230928"
    env:
      GHIDRA_LABEL: ${{ matrix.GHIDRA_VERSION }}_${{ matrix.GHIDRA_BUILD_DATE }}
    steps:
    - uses: actions/checkout@v3

    - name: Get latest Ghidra version
      env:
        GHIDRA_URL: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_${{ matrix.GHIDRA_VERSION }}_build/ghidra_${{ matrix.GHIDRA_VERSION }}_PUBLIC_${{ matrix.GHIDRA_BUILD_DATE }}.zip
      run: |
        echo "trying ${{ matrix.GHIDRA_VERSION }} on ${{ matrix.GHIDRA_BUILD_DATE }}"
        mkdir ../Ghidra && wget --no-check-certificate -O ghidra.zip $GHIDRA_URL && unzip ghidra.zip && rm ghidra.zip && mv ghidra* ../Ghidra
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.5
    - name: Execute Gradle build  
      env:
        GHIDRA_INSTALL_DIR: ${{ github.workspace }}/../Ghidra/ghidra_${{ matrix.GHIDRA_VERSION }}_PUBLIC
      run: |
        gradle build
        gradle
    - name: Cleanup PC extesion zip file
      run: |
        cd dist
        mv *.zip pc.zip
        unzip pc.zip
        rm -rf pc.zip ${{ github.event.repository.name }}/.github
    - name: Archive PC extension zip file
      uses: actions/upload-artifact@v3
      with:
        name: pickled_canary-${{ env.GHIDRA_LABEL }}
        path: dist
